version: '3.7'

networks:
  stock_network:
    name: stock_network

services:
  stock:
    container_name: stock-service
    build:
      context: ./stock-service
      dockerfile: ./Dockerfile
      target: development
    restart: unless-stopped
    command: npm run start:debug
    environment:
      - PORT=3000
    volumes:
      - ./stock-service:/app
      - /app/node_modules
    networks:
      stock_network:
    ports:
      - 3041:3000
      - 9252:9252

  api:
    container_name: stock-api
    build:
      context: ./api-service
      dockerfile: ./Dockerfile
      target: development
    restart: unless-stopped
    command: npm run start:debug
    environment:
      - PORT=3040
    volumes:
      - ./api-service:/app
      - /app/node_modules
    networks:
      stock_network:
    ports:
      - 3040:3040
      - 9251:9251

  mongo:
    image: mongo:4.4
    container_name: stock-mongo
    networks:
      stock_network:
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=stock
      - MONGO_INITDB_ROOT_PASSWORD=stockpass
    volumes:
      - ./.data/dbdata:/data/db
    ports:
      - '27018:27017'
    restart: unless-stopped